name: Test

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-comment:
    uses: rednafi/i-have-seen@v1
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "issues"

  add-pr-comment:
    uses: rednafi/i-have-seen@v1
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "pull_request"
