name: Test

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  add-issue-comment:
    if: ${{ github.event.label.name == 'bug' }}
    uses: rednafi/i-have-seen/.github/workflows/seen.yml@v1
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "issues"

  add-pr-comment:
    if: ${{ github.event.label.name == 'bug' }}
    uses: rednafi/i-have-seen/.github/workflows/seen.yml@v1
    with:
      message: |
        Simple comment **works**.
         This is another ~line~.

      where: "pull_request"
